### ISSUE TITLE
Example MathJax3 from NPM module

### ISSUE THREAD

**Issue by drochgenius** [mathjax/mj3-demos#9]
Hi,

I am trying to figure out how to use the newly published NPM module for MathJax v3.
Examples I see in this repo seem to be a bit outdated, or at least not apply to consuming the mathjax3 npm module.

I'm just curious to see what the new MathJax will look like, and if there will be any perf improvement.
If you could paste a sample snippet on how to setup a TeX to HTML or SVG pipeline using the NPM module, it would be awesome.

Thanks

**Comment by dpvc** [comment]
@drochgenius, my apologies for not seeing your issue when you posted it.  I just today realized that I'm not getting email from this issue tracker (and have fixed that), so I only just saw you posting.

The examples you want are in the [node demos](https://github.com/mathjax/mj3-demos-node) repository rather than this one.

I'm sure this answer is way too late for you, and I'm sorry to have missed it originally.  Again, my apologies.

**Comment by drochgenius** [comment]
No worries @dpvc ,

Thanks for fixing and getting back to me.
